{% set name = "EQcorrscan" %}
{% set version = "0.3.0" %}
{% set sha256 = "e64c3e81c03a14be11a233c8df925367a55e52108ef01de315b28809b0eed08a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # fn: 0.3.0rc1.tar.gz
  # url: https://github.com/eqcorrscan/EQcorrscan/archive/0.3.0rc1.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - future
    - numpy 1.11.*
    - fftw
    - clangdev 4.*   # [osx]
    - openmp 4.*     # [osx]
    - libcxx 4.*     # [osx]
  run:
    - python
    - setuptools
    - future
    - numpy >=1.11
    - fftw
    - scipy
    - matplotlib
    - obspy
    - bottleneck
    - pyproj
    - fftw
    - h5py
    - openmp >=4     # [osx]
    - libcxx >=4     # [osx]

about:
  home: https://eqcorrscan.github.io
  license: LGPLv3
  license_file: LICENCE.txt
  summary: 'Detection and analysis of repeating and near-repeating earthquakes'
  description: |
    EQcorrscan is a Python package for detection and analysis of repeating
    and near-repeating earthquakes.
  doc_url: http://eqcorrscan.readthedocs.io/
  dev_url: https://github.com/eqcorrscan/eqcorrscan

extra:
  recipe-maintainers:
    - calum-chamberlain
