{% set name = "EQcorrscan" %}
{% set version = "0.3.2" %}
{% set sha256 = "43b082e3190958fc5110c5d3db15c80cf441d05328c82758ff3cf41b52a722ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: {{ sha256 }}
#  fn: 0.3.3rc0.tar.gz
#  url: https://github.com/eqcorrscan/EQcorrscan/archive/0.3.2rc0.tar.gz

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - future
    - numpy
    - fftw
    - clangdev 4.*   # [osx]
    - openmp 4.*     # [osx]
    - libcxx 4.*     # [osx]
  run:
    - python
    - setuptools
    - future
    - {{ pin_compatible('numpy') }}
    - fftw
    - scipy
    - matplotlib
    - obspy
    - bottleneck
    - pyproj
    - fftw
    - h5py
    - openmp >=4     # [osx]
    - libcxx >=4     # [osx]

about:
  home: http://eqcorrscan.readthedocs.io/
  license: LGPLv3
  license_file: LICENCE.txt
  summary: 'Detection and analysis of repeating and near-repeating earthquakes'
  description: |
    EQcorrscan is a Python package for detection and analysis of repeating
    and near-repeating earthquakes.
  doc_url: http://eqcorrscan.readthedocs.io/
  dev_url: https://github.com/eqcorrscan/eqcorrscan

extra:
  recipe-maintainers:
    - calum-chamberlain
