{% set name = "EQcorrscan" %}
{% set version = "0.4.1rc0" %}
{% set sha256 = "8957e7373b5998f108af57406ebcf06358f6da24ca2c402bee38433c4d044511" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #  fn: {{ name }}-{{ version }}.tar.gz
  #  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #  sha256: {{ sha256 }}
  fn: 0.4.1rc0.tar.gz
  url: https://github.com/eqcorrscan/EQcorrscan/archive/0.4.1rc0.tar.gz

build:
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - future
    - numpy
    - fftw
    - clangdev 4.*   # [osx]
    - openmp 4.*     # [osx]
    - libcxx 4.*     # [osx]
  run:
    - python
    - setuptools
    - future
    - {{ pin_compatible('numpy') }}
    - fftw
    - scipy
    - matplotlib-base
    - obspy
    - bottleneck
    - pyproj
    - fftw
    - pyfftw
    - h5py
    - openmp >=4     # [osx]
    - libcxx >=4     # [osx]

about:
  home: http://eqcorrscan.readthedocs.io/
  license: LGPLv3
  license_file: LICENCE.txt
  summary: 'Detection and analysis of repeating and near-repeating earthquakes'
  description: |
    EQcorrscan is a Python package for detection and analysis of repeating
    and near-repeating earthquakes.
  doc_url: http://eqcorrscan.readthedocs.io/
  dev_url: https://github.com/eqcorrscan/eqcorrscan

extra:
  recipe-maintainers:
    - calum-chamberlain
