{% set name = "EQcorrscan" %}
{% set version = "0.4.4" %}
{% set sha256 = "70cdebade97d6ddd05dbd347f7bebced66e8163dd8817259bf080302c2e1c69d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  #   fn: 0.4.4rc0.tar.gz
  #   url: https://github.com/eqcorrscan/EQcorrscan/archive/0.4.4rc0.tar.gz

build:
  skip: true  # [win and py==38]
  number: 1


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - future
    - numpy
    - fftw
    - llvm-openmp >=4.0.1  # [osx]
  run:
    - python
    - setuptools
    - future
    - {{ pin_compatible('numpy') }}
    - fftw
    - scipy <1.9.0
    - matplotlib-base
    - obspy
    - bottleneck
    - pyproj
    - pyfftw <=0.12
    - h5py
    - llvm-openmp >=4.0.1  # [osx]

about:
  home: http://eqcorrscan.readthedocs.io/
  license: LGPL-3.0-or-later
  license_file: LICENCE.txt
  summary: Detection and analysis of repeating and near-repeating earthquakes
  description: |
    EQcorrscan is a Python package for detection and analysis of repeating
    and near-repeating earthquakes.
  doc_url: http://eqcorrscan.readthedocs.io/
  dev_url: https://github.com/eqcorrscan/eqcorrscan

extra:
  recipe-maintainers:
    - calum-chamberlain
