travis:
  secure:
    BINSTAR_TOKEN: lQxEm2JJs+Uzq44tHgWPyDEMX/OxGIF8MAmX6dGXK1eDbIhV9mUWBNZgnhNBDp9tnpo6+Z0/a9SaeK10h1bte+YaNVyxI3hlAJzrAyIaMoDLciwnWGPSXt9wM2J1zY6ZRV6sdtsYNeXOGHQvjpJn6MKbCqUn31Q0Myitgc5HPLyGvZs5CCNHfg3+WpB/RQGqOC8s/8NoPXCfp0so2S0r5MiXisf4nB4Yu/9CaA01eBRbmuyQZJT0jydgS+ie469SbgXAv1lTFCHyqXmoQUBmFRjbtEH3H6/X6M4rQQSwHBMXXSCiBUgaJ/v2DptVN++3k6TQiI4c7DLlhWwU0jN2iszwNcSeC7Fm6YkRJHz+L9iQFRYJyBkhr1vLclujtGftpHYuOSj7YFNwopmm/C4gFfps+6zRjqfN7Uz4bsnTkNYyXFRoHEhTywzU8fas2PQxXflUU50UrV295kbYcE7JeW0jB5eOFyfxsqzW+4aAPPorVY0wTGWBbBK9bi0mTjrXRayrciMAdO+fVvhYw/IHC1maOFQ+k/qn2Vx/xlKKZ8Tv/WxHzPLipZJhWDL/4089v1v7pBKUttrNPuJqYLuGoAb159PMw2j85p3i8a+lmg6Vz7UIuhHDRgxcJVdDvCSDWoftMTiABNJ6qKoSd0q5xmtHLH3NQrvSAKy50RoYVLw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
